//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliceApi.Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppConfig
    {
        public System.Guid AppConfigId { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
        public string ApiClient { get; set; }
        public string ApiClientId { get; set; }
        public string ApiClientSecret { get; set; }
    }
}
