//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliceApi.Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberProfile
    {
        public MemberProfile()
        {
            this.Members = new HashSet<Member>();
        }
    
        public System.Guid MemberProfileId { get; set; }
        public string AspNetUserId { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
        public string LocalUserName { get; set; }
        public string PublicUserName { get; set; }
        public string PrimaryEmail { get; set; }
        public string SecondaryEmail { get; set; }
        public string ProfileDescription { get; set; }
        public string ProfileTimeZone { get; set; }
        public string ProfileLanguage { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<Member> Members { get; set; }
    }
}
