//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliceApi.Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public System.Guid MemberId { get; set; }
        public System.Guid MemberProfileId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PreferredName { get; set; }
        public int MemberType { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Gender { get; set; }
        public string FacebookHomeUrl { get; set; }
        public string MemberEmail { get; set; }
    
        public virtual MemberProfile MemberProfile { get; set; }
    }
}
