//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliceApi.Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int MovieId { get; set; }
        public Nullable<int> Genre { get; set; }
        public string MovieTitle { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string DirectedBy { get; set; }
        public string Summary { get; set; }
        public int MPAAID { get; set; }
        public Nullable<int> LocalRating { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> ReleaseYear { get; set; }
        public string Runtime { get; set; }
        public string WrittenBy { get; set; }
        public string Actors { get; set; }
        public string SpokenLanguage { get; set; }
        public string CountryofOrigin { get; set; }
        public string Awards { get; set; }
        public string PosterImageUrl { get; set; }
        public string imdbRating { get; set; }
    
        public virtual MovieMPAA MovieMPAA { get; set; }
    }
}
