//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliceApi.Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieMPAA
    {
        public MovieMPAA()
        {
            this.Movies = new HashSet<Movie>();
        }
    
        public int MPAAID { get; set; }
        public string MPAAName { get; set; }
    
        public virtual ICollection<Movie> Movies { get; set; }
    }
}
